### ISSUE TITLE
ScriptableObject leak in saved canvas assets

### ISSUE THREAD

**Issue by metzsg** [Baste-RainGames/Node_Editor#156]
Whenever a working copy of a canvas is saved, if custom node implementations require extra scriptable objects, they are also cloned and added to the saved copy via CopyScriptableObjects() (a great feature!).  However, the saved copy never gets rid of old clones of the scriptable objects, so repeated saves cause a pileup of old, orphaned scriptableObject assets inside the canvas asset. 

It seems like the easiest fix would be to just get the additional scriptable objects from every node during the cleanup of previous save, and destroy them as well.  I am testing this out now.

Thanks for this great framework!  It has been immensely helpful.

**Comment by Seneral** [comment]
Ah, thanks for reporting:) Actually, the asset is only 're-used' when overwriting canvases of the same type, in order to keep references to it intact. So, to fix this, [this block](https://github.com/Seneral/Node_Editor_Framework/blob/develop/Node_Editor/Framework/SaveSystem/NodeEditorSaveManager.cs#L275) is actually relevant. Instead of manually deleting the old save, we could load ALL sub-assets at that path and delete them at once, except the main canvas which is used for referencing (which actually simplifies the code).

**Comment by Seneral** [comment]
Ok, got it. Can you verify [this](https://github.com/Seneral/Node_Editor_Framework/commit/395b11cfbd37b91ecf792a6bfd54ce560b03dc4d) works? thanks:)

**Comment by metzsg** [comment]
This fixes for my faulted test cases.  Looks good.

**Comment by Seneral** [comment]
Cool:)
