### ISSUE TITLE
Error: No ValueConnectionType could be found or created with name 'GameObject'!

### ISSUE THREAD

**Issue by oxi-dev0** [Baste-RainGames/Node_Editor#176]
I have created my own nodes, but custom Connections cause this error: "No ValueConnectionType could be found or created with name 'GameObject'!", I cannot find where I can define new connection types.

Any help would be appreciated, thanks

**Comment by Seneral** [comment]
It's outlined in the documentation [here](https://nodeeditor.seneral.dev/Documentation/Extensions.html#Connections). Following that, it should be pretty straightforward.
Although one thing to take care of, depending on what you want to do, is that GameObjects have restrictions in regards to how they can be stored in nodes.
If you reference Prefabs, that's fine, these references will be stored in the canvas asset.
If you reference GameObjects in scenes however, they will not be stored in the canvas asset, because an asset cannot reference a scene-only objects. If you do need to store Scene GOs, you'll need to save the canvas itself inside the scene (theres a menu item for that).
This might or might not affect you, just a heads up:)
