### ISSUE TITLE
`PlayModeStateChange' could not be found. Are you missing a using directive or an assembly reference?

### ISSUE THREAD

**Issue by Scannell24** [Baste-RainGames/Node_Editor#186]
Getting some errors trying to import this into a blank unity project. 

Diving into EditorApplication shows a playmodeStateChanged function but PlayModeStateChange seems to be a variable so I'm not sure if there's a relation

Using Unity 5.4.2f2

Perhaps my folder structure is off?
![image](https://user-images.githubusercontent.com/10684776/77857669-f1125900-71cc-11ea-97bf-7c907a89c6bb.png)

**Comment by Seneral** [comment]
This is a unity version issue, the playmodeStateChanged callback has been renamed from 2017.2 onward. To make it compatible between versions it should look [like this](https://github.com/Seneral/Node_Editor_Framework/blob/develop/Node_Editor_Framework/Runtime/Utilities/EditorLoadingControl.cs#L35).

However it seems that I forgot this version checking in UndoPro. Will fix tomorrow, have to install an older unity version again first. If you want a quick fix, just implement a similar construct as in the file linked above (with a wrapper function around the older function signature) [in this UndoPro script](https://github.com/Seneral/UndoPro/blob/master/UndoPro/UndoProManager.cs#L78).

Reminds me I should use that new functionality of the new function signature to replace the mess in EditorLoadingControl, at least in newer unity versions. I'm suprised someone still starts projects in Unity 5. Any reason for this, out of curiosity?
There might be a lot of other errors like this, I honestly am not entirely sure, since I did not pay too much attention to keeping more than a few versions of backwards compability.

**Comment by Seneral** [comment]
Fixed in UndoPro and verified that it works.
NEF also needs slight fixing, will do that now.
- AllAroundNode needs a check, due to new AssemblyDefinitionFiles
- background.png.meta is incompatible, recreated in 5.x to fix it
- The DefaultStyle GUISkin in Resources needed to be regenerated (just delete it), need to verify that version works in newer versions
Will test and push soon

**Comment by Seneral** [comment]
And done, see following commits:
NEF: 19840d2
UndoPro: [`94c375e`](https://github.com/Seneral/UndoPro/commit/94c375e74ef31d817afb81661f84b53715378d6d)

In addition to that, if you need to go even farther back (pre 5.5), you might need to convert the serialization version of each relevant asset manually (only stuff like save files, etc).
I made a script for that a while back, check it out [here](https://gist.github.com/Seneral/d88d2079ff17f77f2bd1775aadb8547b).
