### ISSUE TITLE
Toolbar is not showing up

### ISSUE THREAD

**Issue by agentdalecoper** [Baste-RainGames/Node_Editor#189]
Hi guys, node editor is a super cool framework!
Have the issue that the toolbar is not showing up in the node editor. Maybe doing something wrong.
So cannot assign my custom canvas there.
Everything else seems to work nicely.
Using Unity 2020.2.0a10

![image](https://user-images.githubusercontent.com/23356183/85224035-15e32a80-b3d0-11ea-8211-aedc784485e6.png)

**Comment by agentdalecoper** [comment]
Created PR with assumption how to fix it.

**Comment by agentdalecoper** [comment]
The second commit is more correct.

**Comment by Seneral** [comment]
Hey, thanks for reporting and even fixing it.
So they changed it that quickly again, got to like that. Will have to take a look what's up with editor scaling in the newer version, and how it works now. Can't imagine they simply removed it.

**Comment by Seneral** [comment]
Ok took a look at it and it seems I just didn't implement it properly.
The name of CustomEditorUIScale should have given it away - if you don't explicitly set your editor scale, this editorprefs entry will not be created. And if you disable it again (use system standard) it will go to max value to indicate it should not be used.
However since this is only the custom scale, if the system standard is used and it is not 100%, it will still not work, and afaik there is no reliable way to get that.
So I just rewrote it a bit to not need the editor scale in the first place - always best.
